version: '3'
services:
  master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    ports:
      - 8080:8080
      # - 7077:7077
    networks:
      - workbench
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    env_file:
      - ./hadoop.env

  worker:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    ports:
      - 8081:8081
    networks:
      - workbench
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    env_file:
      - ./hadoop.env

networks:
  workbench:
    external: true
